// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGdK9Xf88ofacCh10o50dPiclY1hkDF20',
    appId: '1:541697312399:web:17dd9c3aaeabd33a0e52fa',
    messagingSenderId: '541697312399',
    projectId: 'loveping-d01c1',
    authDomain: 'loveping-d01c1.firebaseapp.com',
    storageBucket: 'loveping-d01c1.firebasestorage.app',
    measurementId: 'G-R5FW0SPYC8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHI-SCDOWNlPWxMYM-54MXtG7kZd0wzaE',
    appId: '1:541697312399:ios:be8e67bd6ccd32780e52fa',
    messagingSenderId: '541697312399',
    projectId: 'loveping-d01c1',
    storageBucket: 'loveping-d01c1.firebasestorage.app',
    iosBundleId: 'com.example.loveping',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHI-SCDOWNlPWxMYM-54MXtG7kZd0wzaE',
    appId: '1:541697312399:ios:be8e67bd6ccd32780e52fa',
    messagingSenderId: '541697312399',
    projectId: 'loveping-d01c1',
    storageBucket: 'loveping-d01c1.firebasestorage.app',
    iosBundleId: 'com.example.loveping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGdK9Xf88ofacCh10o50dPiclY1hkDF20',
    appId: '1:541697312399:web:e70bd77ee64b86e80e52fa',
    messagingSenderId: '541697312399',
    projectId: 'loveping-d01c1',
    authDomain: 'loveping-d01c1.firebaseapp.com',
    storageBucket: 'loveping-d01c1.firebasestorage.app',
    measurementId: 'G-JMZTVGCEJB',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8V3LG8GhBcRTq9zTzLljXBx6DpOgDw0',
    appId: '1:541697312399:android:478f56f0db8bcb6d0e52fa',
    messagingSenderId: '541697312399',
    projectId: 'loveping-d01c1',
    storageBucket: 'loveping-d01c1.firebasestorage.app',
  );
}
